# Pivoting 

For this example, let's look at two datasets. One a voting data from here: https://www.kaggle.com/stevepalley/2016uspresidentialvotebycounty

The other, world happiness data from here: https://www.kaggle.com/unsdsn/world-happiness

This dataset will make use of our merging skills!

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

os.chdir('../Data Manipulation in Python Crash Course/P87-S7-Advanced-Manipulation-Resources/')

dfo = pd.read_csv("pres16results.csv")
dfo.head()

county fips             cand  st  pct_report       votes  total_votes  \
0    NaN   US     Donald Trump  US      0.9951  60350241.0  127592176.0   
1    NaN   US  Hillary Clinton  US      0.9951  60981118.0  127592176.0   
2    NaN   US     Gary Johnson  US      0.9951   4164589.0  127592176.0   
3    NaN   US       Jill Stein  US      0.9951   1255968.0  127592176.0   
4    NaN   US    Evan McMullin  US      0.9951    451636.0  127592176.0   

        pct          lead  
0  0.472993  Donald Trump  
1  0.477938  Donald Trump  
2  0.032640  Donald Trump  
3  0.009844  Donald Trump  
4  0.003540  Donald Trump

In [8]:
dfo.county.unique()  

array([nan, 'Los Angeles County', 'Cook County', ..., 'St. Croix Island',
       'St. John Island', 'St. Thomas Island'], dtype=object)

In [16]:
dfo['county'] == 'Los Angeles County'

0        False
1        False
2        False
3        False
4        False
         ...  
18470    False
18471    False
18472    False
18473    False
18474    False
Name: county, Length: 18475, dtype: bool

In [20]:
# boolean indexing
dfo[dfo['county'] == 'Los Angeles County']

county  fips             cand  st  pct_report      votes  \
159  Los Angeles County  6037  Hillary Clinton  CA         1.0  1654626.0   
160  Los Angeles County  6037     Donald Trump  CA         1.0   542591.0   
161  Los Angeles County  6037     Gary Johnson  CA         1.0    56905.0   
162  Los Angeles County  6037       Jill Stein  CA         1.0    46682.0   
163  Los Angeles County  6037   Gloria La Riva  CA         1.0    13471.0   

     total_votes       pct             lead  
159    2314275.0  0.714965  Hillary Clinton  
160    2314275.0  0.234454  Hillary Clinton  
161    2314275.0  0.024589  Hillary Clinton  
162    2314275.0  0.020171  Hillary Clinton  
163    2314275.0  0.005821  Hillary Clinton

In [15]:
dfo.to_numpy()[1]

array([nan, 'US', 'Hillary Clinton', 'US', 0.9951, 60981118.0,
       127592176.0, 0.477937753800829, 'Donald Trump'], dtype=object)

array([nan, 'US', 'Hillary Clinton', 'US', 0.9951, 60981118.0,
       127592176.0, 0.477937753800829, 'Donald Trump'], dtype=object)

In [71]:
# function that returns x if x > 0, else 0
def pos_or_zero(x):
    if x > 0:
        return True
    else:
        return False

x = 'a'

# evaluate data type of x

x > 'A'

True

In [33]:
type(x)

float

In [49]:
print(ord('a'))
print(ord('A'))


97
65


In [46]:
# represent '97' in binary
bin(97)

'0b1100001'

In [72]:
# represent '97' in hexadecimal
hex(97)

'0x61'

In [50]:
# represent binary in decimal
int('01100001', 2)

97

In [73]:
int('61', 16)

97

In [54]:
2**4

16

In [55]:
2* 2* 2 *2

16

In [74]:
lista = [1, 2, 3, 4, 5]

In [76]:
# create for loop to find the number 2 in lista
for i in lista:
    if i == 2:
        print(i)

# lista[1]

2


In [77]:
lista[1]

2

In [84]:
lista = {1:'2', 2:'3', 3:'4'}

for i in lista:
    if i == 2:
        print(i)

2


In [85]:
# find the number 2 in lista
lista[2]

'3'